/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as KlantTokenRouteImport } from './routes/klant.$token'
import { Route as AuthenticatedSchadeberekeningRouteImport } from './routes/_authenticated/schadeberekening'
import { Route as AuthenticatedRegelingsdocumentenRouteImport } from './routes/_authenticated/regelingsdocumenten'
import { Route as AuthenticatedPrecedentenRouteImport } from './routes/_authenticated/precedenten'
import { Route as AuthenticatedNieuweSchadeRouteImport } from './routes/_authenticated/nieuwe-schade'
import { Route as AuthenticatedInstellingenRouteImport } from './routes/_authenticated/instellingen'
import { Route as AuthenticatedExcelImportRouteImport } from './routes/_authenticated/excel-import'
import { Route as AuthenticatedDossiersRouteImport } from './routes/_authenticated/dossiers'
import { Route as AuthenticatedBestekanalyseRouteImport } from './routes/_authenticated/bestekanalyse'
import { Route as AuthenticatedAuditrapportRouteImport } from './routes/_authenticated/auditrapport'
import { Route as AuthenticatedDossiersIdRouteImport } from './routes/_authenticated/dossiers.$id'
import { Route as ApiPublicCronAbexFetchRouteImport } from './routes/api/public/cron/abex-fetch'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const KlantTokenRoute = KlantTokenRouteImport.update({
  id: '/klant/$token',
  path: '/klant/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchadeberekeningRoute =
  AuthenticatedSchadeberekeningRouteImport.update({
    id: '/schadeberekening',
    path: '/schadeberekening',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegelingsdocumentenRoute =
  AuthenticatedRegelingsdocumentenRouteImport.update({
    id: '/regelingsdocumenten',
    path: '/regelingsdocumenten',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrecedentenRoute =
  AuthenticatedPrecedentenRouteImport.update({
    id: '/precedenten',
    path: '/precedenten',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNieuweSchadeRoute =
  AuthenticatedNieuweSchadeRouteImport.update({
    id: '/nieuwe-schade',
    path: '/nieuwe-schade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstellingenRoute =
  AuthenticatedInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExcelImportRoute =
  AuthenticatedExcelImportRouteImport.update({
    id: '/excel-import',
    path: '/excel-import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDossiersRoute = AuthenticatedDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBestekanalyseRoute =
  AuthenticatedBestekanalyseRouteImport.update({
    id: '/bestekanalyse',
    path: '/bestekanalyse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditrapportRoute =
  AuthenticatedAuditrapportRouteImport.update({
    id: '/auditrapport',
    path: '/auditrapport',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDossiersIdRoute = AuthenticatedDossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDossiersRoute,
} as any)
const ApiPublicCronAbexFetchRoute = ApiPublicCronAbexFetchRouteImport.update({
  id: '/api/public/cron/abex-fetch',
  path: '/api/public/cron/abex-fetch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auditrapport': typeof AuthenticatedAuditrapportRoute
  '/bestekanalyse': typeof AuthenticatedBestekanalyseRoute
  '/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/excel-import': typeof AuthenticatedExcelImportRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/nieuwe-schade': typeof AuthenticatedNieuweSchadeRoute
  '/precedenten': typeof AuthenticatedPrecedentenRoute
  '/regelingsdocumenten': typeof AuthenticatedRegelingsdocumentenRoute
  '/schadeberekening': typeof AuthenticatedSchadeberekeningRoute
  '/klant/$token': typeof KlantTokenRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/api/public/cron/abex-fetch': typeof ApiPublicCronAbexFetchRoute
}
export interface FileRoutesByTo {
  '/auditrapport': typeof AuthenticatedAuditrapportRoute
  '/bestekanalyse': typeof AuthenticatedBestekanalyseRoute
  '/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/excel-import': typeof AuthenticatedExcelImportRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/nieuwe-schade': typeof AuthenticatedNieuweSchadeRoute
  '/precedenten': typeof AuthenticatedPrecedentenRoute
  '/regelingsdocumenten': typeof AuthenticatedRegelingsdocumentenRoute
  '/schadeberekening': typeof AuthenticatedSchadeberekeningRoute
  '/klant/$token': typeof KlantTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/api/public/cron/abex-fetch': typeof ApiPublicCronAbexFetchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/auditrapport': typeof AuthenticatedAuditrapportRoute
  '/_authenticated/bestekanalyse': typeof AuthenticatedBestekanalyseRoute
  '/_authenticated/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/_authenticated/excel-import': typeof AuthenticatedExcelImportRoute
  '/_authenticated/instellingen': typeof AuthenticatedInstellingenRoute
  '/_authenticated/nieuwe-schade': typeof AuthenticatedNieuweSchadeRoute
  '/_authenticated/precedenten': typeof AuthenticatedPrecedentenRoute
  '/_authenticated/regelingsdocumenten': typeof AuthenticatedRegelingsdocumentenRoute
  '/_authenticated/schadeberekening': typeof AuthenticatedSchadeberekeningRoute
  '/klant/$token': typeof KlantTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/api/public/cron/abex-fetch': typeof ApiPublicCronAbexFetchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditrapport'
    | '/bestekanalyse'
    | '/dossiers'
    | '/excel-import'
    | '/instellingen'
    | '/nieuwe-schade'
    | '/precedenten'
    | '/regelingsdocumenten'
    | '/schadeberekening'
    | '/klant/$token'
    | '/dossiers/$id'
    | '/api/public/cron/abex-fetch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auditrapport'
    | '/bestekanalyse'
    | '/dossiers'
    | '/excel-import'
    | '/instellingen'
    | '/nieuwe-schade'
    | '/precedenten'
    | '/regelingsdocumenten'
    | '/schadeberekening'
    | '/klant/$token'
    | '/'
    | '/dossiers/$id'
    | '/api/public/cron/abex-fetch'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/auditrapport'
    | '/_authenticated/bestekanalyse'
    | '/_authenticated/dossiers'
    | '/_authenticated/excel-import'
    | '/_authenticated/instellingen'
    | '/_authenticated/nieuwe-schade'
    | '/_authenticated/precedenten'
    | '/_authenticated/regelingsdocumenten'
    | '/_authenticated/schadeberekening'
    | '/klant/$token'
    | '/_authenticated/'
    | '/_authenticated/dossiers/$id'
    | '/api/public/cron/abex-fetch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  KlantTokenRoute: typeof KlantTokenRoute
  ApiPublicCronAbexFetchRoute: typeof ApiPublicCronAbexFetchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/klant/$token': {
      id: '/klant/$token'
      path: '/klant/$token'
      fullPath: '/klant/$token'
      preLoaderRoute: typeof KlantTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schadeberekening': {
      id: '/_authenticated/schadeberekening'
      path: '/schadeberekening'
      fullPath: '/schadeberekening'
      preLoaderRoute: typeof AuthenticatedSchadeberekeningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/regelingsdocumenten': {
      id: '/_authenticated/regelingsdocumenten'
      path: '/regelingsdocumenten'
      fullPath: '/regelingsdocumenten'
      preLoaderRoute: typeof AuthenticatedRegelingsdocumentenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/precedenten': {
      id: '/_authenticated/precedenten'
      path: '/precedenten'
      fullPath: '/precedenten'
      preLoaderRoute: typeof AuthenticatedPrecedentenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nieuwe-schade': {
      id: '/_authenticated/nieuwe-schade'
      path: '/nieuwe-schade'
      fullPath: '/nieuwe-schade'
      preLoaderRoute: typeof AuthenticatedNieuweSchadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instellingen': {
      id: '/_authenticated/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof AuthenticatedInstellingenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/excel-import': {
      id: '/_authenticated/excel-import'
      path: '/excel-import'
      fullPath: '/excel-import'
      preLoaderRoute: typeof AuthenticatedExcelImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dossiers': {
      id: '/_authenticated/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof AuthenticatedDossiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bestekanalyse': {
      id: '/_authenticated/bestekanalyse'
      path: '/bestekanalyse'
      fullPath: '/bestekanalyse'
      preLoaderRoute: typeof AuthenticatedBestekanalyseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditrapport': {
      id: '/_authenticated/auditrapport'
      path: '/auditrapport'
      fullPath: '/auditrapport'
      preLoaderRoute: typeof AuthenticatedAuditrapportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dossiers/$id': {
      id: '/_authenticated/dossiers/$id'
      path: '/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedDossiersIdRouteImport
      parentRoute: typeof AuthenticatedDossiersRoute
    }
    '/api/public/cron/abex-fetch': {
      id: '/api/public/cron/abex-fetch'
      path: '/api/public/cron/abex-fetch'
      fullPath: '/api/public/cron/abex-fetch'
      preLoaderRoute: typeof ApiPublicCronAbexFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDossiersRouteChildren {
  AuthenticatedDossiersIdRoute: typeof AuthenticatedDossiersIdRoute
}

const AuthenticatedDossiersRouteChildren: AuthenticatedDossiersRouteChildren = {
  AuthenticatedDossiersIdRoute: AuthenticatedDossiersIdRoute,
}

const AuthenticatedDossiersRouteWithChildren =
  AuthenticatedDossiersRoute._addFileChildren(
    AuthenticatedDossiersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditrapportRoute: typeof AuthenticatedAuditrapportRoute
  AuthenticatedBestekanalyseRoute: typeof AuthenticatedBestekanalyseRoute
  AuthenticatedDossiersRoute: typeof AuthenticatedDossiersRouteWithChildren
  AuthenticatedExcelImportRoute: typeof AuthenticatedExcelImportRoute
  AuthenticatedInstellingenRoute: typeof AuthenticatedInstellingenRoute
  AuthenticatedNieuweSchadeRoute: typeof AuthenticatedNieuweSchadeRoute
  AuthenticatedPrecedentenRoute: typeof AuthenticatedPrecedentenRoute
  AuthenticatedRegelingsdocumentenRoute: typeof AuthenticatedRegelingsdocumentenRoute
  AuthenticatedSchadeberekeningRoute: typeof AuthenticatedSchadeberekeningRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditrapportRoute: AuthenticatedAuditrapportRoute,
  AuthenticatedBestekanalyseRoute: AuthenticatedBestekanalyseRoute,
  AuthenticatedDossiersRoute: AuthenticatedDossiersRouteWithChildren,
  AuthenticatedExcelImportRoute: AuthenticatedExcelImportRoute,
  AuthenticatedInstellingenRoute: AuthenticatedInstellingenRoute,
  AuthenticatedNieuweSchadeRoute: AuthenticatedNieuweSchadeRoute,
  AuthenticatedPrecedentenRoute: AuthenticatedPrecedentenRoute,
  AuthenticatedRegelingsdocumentenRoute: AuthenticatedRegelingsdocumentenRoute,
  AuthenticatedSchadeberekeningRoute: AuthenticatedSchadeberekeningRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  KlantTokenRoute: KlantTokenRoute,
  ApiPublicCronAbexFetchRoute: ApiPublicCronAbexFetchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
